modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/beholderface/Enlightened-Psionics/issues"
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="icon.png"
authors="${mod_authors}" #optional

description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
modId="hexcasting"
mandatory=true
versionRange="[0.11.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="psi"
mandatory=true
versionRange="[${psi_version},)"
ordering="NONE"
side="BOTH"